services:
  orac-stt:
    build: .
    container_name: orac-stt
    image: orac-stt:latest

    # GPU support for Orin Nano
    runtime: nvidia

    # Environment configuration (consolidated single block)
    environment:
      # Timezone (Switzerland)
      - TZ=Europe/Zurich
      # GPU settings
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      # Python settings
      - PYTHONUNBUFFERED=1
      - LD_LIBRARY_PATH=/usr/local/lib/whisper
      # Service configuration
      - LOG_LEVEL=INFO
      - MODEL_NAME=whisper-tiny-int8
      - MODEL_CACHE_DIR=/app/models
      - ORAC_COMMAND_API_URL=http://localhost:8001/command
      - ORAC_API_PORT=7272
      - USE_WHISPER_CPP=true
      
    # Volume mounts - ensure proper permissions
    volumes:
      # Timezone configuration
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      # Model cache - persistent across restarts
      - ./models:/app/models:rw
      # Certificates for mTLS
      - ./certs:/app/certs:ro
      # Logs (optional, can use docker logs instead)
      - ./logs:/app/logs:rw
      # Data directory
      - ./data:/app/data:rw
      # Debug recordings
      - ./debug_recordings:/app/debug_recordings:rw
      # whisper.cpp binaries and libraries (built on Jetson)
      - ./third_party/whisper_cpp/bin:/app/third_party/whisper_cpp/bin:ro
      - ./third_party/whisper_cpp/models:/app/models/whisper_cpp:ro
      - ./third_party/whisper_cpp/lib:/usr/local/lib/whisper:ro
      
    # Port mappings
    ports:
      - "7272:7272"  # HTTP API, Health, Metrics
      
    # Resource limits for Orin Nano
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
          
    # Restart policy
    restart: unless-stopped
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7272/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s
      
    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "app=orac-stt"

# Networks (if needed for multi-service setup)
networks:
  default:
    driver: bridge
